-- Store user-created agents
CREATE TABLE IF NOT EXISTS agents (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    topic TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_run TIMESTAMP,
    is_active BOOLEAN DEFAULT 1
);

-- Store agent configurations (generated by Claude)
CREATE TABLE IF NOT EXISTS agent_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id INTEGER NOT NULL UNIQUE,
    insight_schema TEXT NOT NULL,      -- JSON array of field definitions
    quality_criteria TEXT NOT NULL,    -- JSON with evaluation criteria
    search_queries TEXT NOT NULL,      -- JSON array of search queries
    extraction_prompt TEXT NOT NULL,   -- Prompt for extracting insights
    aggregate_prompt TEXT NOT NULL,    -- Prompt for aggregate analysis
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

-- Store example URLs provided by user
CREATE TABLE IF NOT EXISTS agent_examples (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id INTEGER NOT NULL,
    url TEXT NOT NULL,
    reasoning TEXT,  -- Why user considers this high quality
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

-- Store discovered sources (before extraction)
CREATE TABLE IF NOT EXISTS discovered_sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id INTEGER NOT NULL,
    url TEXT NOT NULL,
    quality_score REAL,
    reasoning TEXT,
    discovered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_processed BOOLEAN DEFAULT 0,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    UNIQUE(agent_id, url)
);

-- Store extracted insights (dynamic schema) - NEW VERSION
CREATE TABLE IF NOT EXISTS insights_v2 (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id INTEGER NOT NULL,
    source_id INTEGER,  -- Reference to discovered_sources
    url TEXT NOT NULL,
    source_name TEXT,
    date_crawled TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    extracted_data TEXT NOT NULL,  -- JSON with dynamic fields based on agent schema
    raw_content TEXT,
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE,
    FOREIGN KEY (source_id) REFERENCES discovered_sources(id)
);

-- Store aggregate analyses
CREATE TABLE IF NOT EXISTS aggregate_analyses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    agent_id INTEGER NOT NULL,
    analysis_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    analysis_data TEXT NOT NULL,  -- JSON with patterns/opportunities
    insights_count INTEGER,  -- Number of insights analyzed
    FOREIGN KEY (agent_id) REFERENCES agents(id) ON DELETE CASCADE
);

-- User interests (what topics they care about)
CREATE TABLE IF NOT EXISTS user_interests (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER DEFAULT 1,  -- Single user for MVP
    topic TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User engagement with insights (likes, bookmarks, skips)
CREATE TABLE IF NOT EXISTS insight_engagement (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER DEFAULT 1,
    insight_id INTEGER NOT NULL,
    action TEXT NOT NULL,  -- 'like', 'bookmark', 'skip', 'share'
    engaged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (insight_id) REFERENCES insights_v2(id)
);

-- Feed queue (pre-generated insights ready to show)
CREATE TABLE IF NOT EXISTS feed_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER DEFAULT 1,
    insight_id INTEGER NOT NULL,
    relevance_score REAL,  -- How relevant to user interests (0-1)
    shown BOOLEAN DEFAULT 0,
    shown_at TIMESTAMP,
    position INTEGER,  -- Order in feed
    FOREIGN KEY (insight_id) REFERENCES insights_v2(id)
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_insights_v2_agent ON insights_v2(agent_id);
CREATE INDEX IF NOT EXISTS idx_insights_v2_date ON insights_v2(date_crawled);
CREATE INDEX IF NOT EXISTS idx_discovered_agent ON discovered_sources(agent_id);
CREATE INDEX IF NOT EXISTS idx_discovered_processed ON discovered_sources(is_processed);
CREATE INDEX IF NOT EXISTS idx_aggregate_agent ON aggregate_analyses(agent_id);
CREATE INDEX IF NOT EXISTS idx_aggregate_date ON aggregate_analyses(analysis_date);
CREATE INDEX IF NOT EXISTS idx_feed_queue_shown ON feed_queue(shown);
CREATE INDEX IF NOT EXISTS idx_feed_queue_relevance ON feed_queue(relevance_score);
CREATE INDEX IF NOT EXISTS idx_engagement_insight ON insight_engagement(insight_id);
CREATE INDEX IF NOT EXISTS idx_engagement_action ON insight_engagement(action);
